# Generated by Django 3.1.7 on 2021-02-28 05:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newcars', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newcar',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=9, verbose_name='Цена'),
        ),
    ]
